/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-11-22 16:30:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class formularioCitas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<link rel=\"icon\" href=\"../../favicon.ico\">\n");
      out.write("<link rel=\"canonical\"\n");
      out.write("\thref=\"https://getbootstrap.com/docs/3.4/examples/signin/\">\n");
      out.write("\n");
      out.write("<title>Pedir Cita</title>\n");
      out.write("\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"datePicker/css/bootstrap-datepicker.css\">\n");
      out.write("<script src=\"datePicker/js/bootstrap-datepicker.min.js\"></script>\n");
      out.write("\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js\"></script>\n");
      out.write("\n");
      out.write("<script src=\"datePicker/locales/bootstrap-datepicker.es.min.js\"></script>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.min.css\">\n");
      out.write("\n");
      out.write("<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\n");
      out.write("<link href=\"../../assets/css/ie10-viewport-bug-workaround.css\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"signin.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\n");
      out.write("<!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\n");
      out.write("<script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>\n");
      out.write("\n");
      out.write("<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write(".bd-placeholder-img {\n");
      out.write("\tfont-size: 1.125rem;\n");
      out.write("\ttext-anchor: middle;\n");
      out.write("\t-webkit-user-select: none;\n");
      out.write("\t-moz-user-select: none;\n");
      out.write("\t-ms-user-select: none;\n");
      out.write("\tuser-select: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("@media ( min-width : 768px) {\n");
      out.write("\t.bd-placeholder-img-lg {\n");
      out.write("\t\tfont-size: 3.5rem;\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<!-- Custom styles for this template -->\n");
      out.write("<link href=\"starter-template.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar navbar-expand-md navbar-dark bg-dark fixed-top\">\n");
      out.write("\t\t<a class=\"navbar-brand\" href=\"/citas\">THE GOOD HEALTH</a>\n");
      out.write("\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\n");
      out.write("\t\t\tdata-target=\"#navbarsExampleDefault\"\n");
      out.write("\t\t\taria-controls=\"navbarsExampleDefault\" aria-expanded=\"false\"\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t</button>\n");
      out.write("\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"navbarsExampleDefault\">\n");
      out.write("\t\t\t<ul class=\"navbar-nav mr-auto\">\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"/citas\"\n");
      out.write("\t\t\t\t\ttabindex=\"-1\" aria-disabled=\"true\">Mis citas</a></li>\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\">Pedir\n");
      out.write("\t\t\t\t\t\tcita <span class=\"sr-only\">(current)</span>\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown\"><a\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"dropdown01\"\n");
      out.write("\t\t\t\t\tdata-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Cuenta</a>\n");
      out.write("\t\t\t\t\t<div class=\"dropdown-menu\" aria-labelledby=\"dropdown01\">\n");
      out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"#\">Mi Perfil</a> <a\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"#\">Información</a> <a\n");
      out.write("\t\t\t\t\t\t\tclass=\"dropdown-item\" href=\"/\">Cerrar sesión</a>\n");
      out.write("\t\t\t\t\t</div></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Buscar\"\n");
      out.write("\t\t\t\t\taria-label=\"Search\">\n");
      out.write("\t\t\t\t<button class=\"btn btn-secondary my-2 my-sm-0\" type=\"submit\">Buscar</button>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<main role=\"main\" class=\"container\">\n");
      out.write("\t\t<div class=\"span\">\n");
      out.write("\t\t\t<div></div>\n");
      out.write("\t\t\t<div class=\"container center\">\n");
      out.write("\t\t\t<div class=\"hero-unit\">\n");
      out.write("\t\t\t\t<br></br>\n");
      out.write("\t\t\t\t<br></br>\n");
      out.write("\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t<div></div>\n");
      out.write("\t\t\t\t<div class=\"row align-items-center\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8\">\n");
      out.write("\t\t\t\t\t\t<div class=\"card\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"card-body\">\n");
      out.write("\t\t\t\t\t\t\t\t<h4>Formulario de Citas</h4>\n");
      out.write("\t\t\t\t\t\t\t\t<p>Para pedir una cita, rellene todos los campos que\n");
      out.write("\t\t\t\t\t\t\t\t\tencontrará a continuación para solicitar la cita deseada,\n");
      out.write("\t\t\t\t\t\t\t\t\tdespués pulse en el botón de Solicitar cita.</p>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-1\"></div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<br></br>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"container center\">\n");
      out.write("\t\t\t\t<div class=\"jumbotron jumbotron-fluid\">\n");
      out.write("\t\t\t\t\t<div align='center'>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 mb-3\">\n");
      out.write("\t\t\t\t\t\t<label for=\"especialidad\">Especialidad</label> \n");
      out.write("\t\t\t\t\t\t<select class=\"form-control form-control-lg align:center\" id=\"especialidad\">\n");
      out.write("\t\t\t\t\t\t\t<option selected=\"selected\" disabled=true></option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br></br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 mb-3\">\n");
      out.write("\t\t\t\t\t\t<label for=\"fecha_ini\">Día</label> <input disabled type=\"text\"\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\tid=\"fecha_ini\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t<div class=\"invalid-feedback\">Información necesaria.</div>\n");
      out.write("\t\t\t\t\t\t<label id=\"fecha\"></label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<br></br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6 mb-3\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<label for=\"hora\">Hora</label> <select disabled\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"form-control form-control-lg align:center\" id=\"hora\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t\t<label id=\"noHayHora\"></label>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t<br></br>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t<hr class=\"mb-4\">\n");
      out.write("\t\t\t\t\t\t\t<a id=\"pedircita\" class=\"btn btn-primary btn-large\" type=\"submit\">Solicitar\n");
      out.write("\t\t\t\t\t\t\t\tcita</a> <a href=\"/citas\" class=\"btn btn-primary btn-large\" type=\"submit\">Volver\n");
      out.write("\t\t\t\t\t\t\t\tatrás</a>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<br></br>\n");
      out.write("\t</main>\n");
      out.write("\t<!-- /.container -->\n");
      out.write("\n");
      out.write("\t<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"\n");
      out.write("\t\tintegrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\"\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.7.8/angular.min.js\"></script>\n");
      out.write("\t<script\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js\"></script>\n");
      out.write("\t<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\tjQuery(document).ready(function($) {\n");
      out.write("\t\t\t\t\t\t\t/*\n");
      out.write("\t\t\t\t\t\t\t * Control para que no acceda a travï¿½s de la url a alguna pï¿½gina que no sea el home\n");
      out.write("\t\t\t\t\t\t\t * Hay que ponerlo en todos los jsp que se hagan prï¿½ximamente\n");
      out.write("\t\t\t\t\t\t\t */\n");
      out.write("\t\t\t\t\t\t\tvar referrer = document.referrer;\n");
      out.write("\t\t\t\t\t\t\tif (referrer != 'http://localhost:8080/citas'\n");
      out.write("\t\t\t\t\t\t\t\t\t&& referrer != 'https://the-good-health.herokuapp.com/citas') {\n");
      out.write("\t\t\t\t\t\t\t\tvar forma = document.forms[0];\n");
      out.write("\t\t\t\t\t\t\t\tforma.action = \"/error\";\n");
      out.write("\t\t\t\t\t\t\t\tforma.submit();\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\tvar jsoUser = JSON.parse(sessionStorage.usuario);\n");
      out.write("\t\t\t\t\t\t\tvar centro = jsoUser.resultado.paciente.centro;\n");
      out.write("\t\t\t\t\t\t\tif(centro==\"Sin asignar\"){\n");
      out.write("\t\t\t\t\t\t\t\tswal({\n");
      out.write("\t\t\t\t\t\t\t\t\ttitle : \"Lo sentimos\",\n");
      out.write("\t\t\t\t\t\t\t\t\ttext : \"Aún no puede solicitar citas, el gestor tiene que asignarle un centro médico y el grupo de médicos que le atenderán en dicho centro. Disculpe las molestias\",\n");
      out.write("\t\t\t\t\t\t\t\t\ticon : \"error\",\n");
      out.write("\t\t\t\t\t\t\t\t}).then(function() {\n");
      out.write("\t\t\t\t\t\t\t\t\twindow.location.href = \"/citas\";\n");
      out.write("\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\tcargarDatosFormulario();\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t\t\t$('#pedircita').click(function(event) {\n");
      out.write("\t\t\t\tif (!(comprobarFecha(document\n");
      out.write("\t\t\t\t\t\t.getElementById(\"fecha_ini\").value) + comprobarHora(document\n");
      out.write("\t\t\t\t\t\t.getElementById(\"hora\").value)) != 0) {\n");
      out.write("\t\t\t\t\tevent.preventDefault();\n");
      out.write("\t\t\t\t\tenviarDatos();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t        $(\"#especialidad\").change(function(){\n");
      out.write("\t        \t$('#noHayHora').html(\"\");\n");
      out.write("\t        \tif($('#fecha_ini').datepicker('getDate')!=null){\n");
      out.write("\t        \t\t$('#fecha_ini').datepicker('setDate', null);\n");
      out.write("\t        \t}\n");
      out.write("\t        \tvar numOptions = document.getElementById(\"especialidad\").length;\n");
      out.write("\t        \tvar especialidadSeleccionada = document.getElementById(\"especialidad\").value;\n");
      out.write("\t        \tgetDNIMedico(especialidadSeleccionada);\n");
      out.write("\t        });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t$(document).ready(function(){\n");
      out.write("\t        $(\"#fecha_ini\").change(function(){\n");
      out.write("\t        \t$('#fecha').html(\"\");\n");
      out.write("\t        \tvar jsoHorario = JSON.parse(sessionStorage.horario);\n");
      out.write("\t\t\t\tvar horario = jsoHorario.horarioMedico.horario;\n");
      out.write("\t\t\t\tvar numHoras=0;\n");
      out.write("\t\t\t\tvar weekday=new Array(7);\n");
      out.write("\t\t\t\tweekday[0]=\"Domingo\";\n");
      out.write("\t\t\t\tweekday[1]=\"Lunes\";\n");
      out.write("\t\t\t\tweekday[2]=\"Martes\";\n");
      out.write("\t\t\t\tweekday[3]=\"Miércoles\";\n");
      out.write("\t\t\t\tweekday[4]=\"Jueves\";\n");
      out.write("\t\t\t\tweekday[5]=\"Viernes\";\n");
      out.write("\t\t\t\tweekday[6]=\"Sábado\";\n");
      out.write("\t\t\t\tvar dateString = $('#fecha_ini').val();\n");
      out.write("\t\t\t\tvar dateParts = dateString.split(\"/\");\n");
      out.write("\t\t\t\tvar dateObject = new Date(+dateParts[2], dateParts[1] - 1, +dateParts[0]);\n");
      out.write("\t\t\t\tvar diaSemana = weekday[dateObject.getDay()];\n");
      out.write("\t\t\t\tconsole.log(diaSemana);\n");
      out.write("\t\t\t\tfor(var j=0; j<horario.length; j++){\n");
      out.write("\t\t\t\t\tif(diaSemana==horario[j][0]){\n");
      out.write("\t\t\t\t\t\tnumHoras++;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tconsole.log(numHoras);\n");
      out.write("\t\t\t\tvar horasDisponibles = new Array(numHoras);\n");
      out.write("\t\t\t\tvar k=0;\n");
      out.write("\t\t\t\tfor(var i=0; i<horario.length; i++){\n");
      out.write("\t\t\t\t\tif(diaSemana==horario[i][0]){\n");
      out.write("\t\t\t\t\t\thorasDisponibles[k]=horario[i][1];\n");
      out.write("\t\t\t\t\t\tconsole.log(horasDisponibles[k]);\n");
      out.write("\t\t\t\t\t\tk++;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t//Filtrar aquí haciendo una petición que me devuelva las citas que haya ese día de ese médico\n");
      out.write("\t\t\t\t//Buscar en la BD por dniMedico y por día. Conseguir las horas y las que coincidan con horas disponibles\n");
      out.write("\t\t\t\t//Se eliminan del vector y ya se guarda el sessionStorage con las horas buenas\n");
      out.write("\t\t\t\tvar dniMedico = jsoHorario.horarioMedico.DNI;\n");
      out.write("\t\t\t\tgetHorasCitasDiaSeleccionado(dateString, dniMedico);\n");
      out.write("\t\t\t\tvar jsoHorasOcu = JSON.parse(sessionStorage.horasOcupadas);\n");
      out.write("\t\t\t\tvar horasOcupadas = jsoHorasOcu.horas;\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif(horasOcupadas.length != 0) {\n");
      out.write("\t\t\t\t\tvar horasDefinitivo = horasDisponibles.filter(function(e) {\n");
      out.write("\t\t\t\t\t    return horasOcupadas.indexOf(e) == -1\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t\tsessionStorage.horas=JSON.stringify(horasDefinitivo);\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\tsessionStorage.horas=JSON.stringify(horasDisponibles);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tif(horasDisponibles.length!=0){\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"hora\").disabled=false;\n");
      out.write("\t\t\t\t\t$('#noHayHora').html(\"\");\n");
      out.write("\t\t\t\t\trellenarHoras();\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\telse {\n");
      out.write("\t\t\t\t\t$('#hora').html(\"\");\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"hora\").disabled=true;\n");
      out.write("\t\t\t\t\tif($(\"#fecha_ini\").datepicker(\"getDate\") != null) {\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t$('#noHayHora').html(\"No hay horas disponibles para este día, seleccione otro.\");\n");
      out.write("\t\t\t\t\t\t$('#noHayHora').css(\"color\", \"red\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t        });\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tfunction getHorasCitasDiaSeleccionado(fecha, dniMedico) {\n");
      out.write("\t\t\tvar data = {\n");
      out.write("\t\t\t\t\tdniMedico : dniMedico,\n");
      out.write("\t\t\t\t\tfecha : fecha,\n");
      out.write("\t\t\t\t\ttipo : \"getCitasDiaMedico\"\n");
      out.write("\t\t\t\t};\n");
      out.write("\t\t\t\tvar url = \"/formularioCitas\";\n");
      out.write("\t\t\t\tvar type = \"POST\";\n");
      out.write("\t\t\t\tvar success;\n");
      out.write("\t\t\t\tvar async= false;\n");
      out.write("\t\t\t\tvar xhrFields;\n");
      out.write("\t\t\t\tvar headers = {\n");
      out.write("\t\t\t\t\t'Content-Type' : 'application/json'\n");
      out.write("\t\t\t\t};\n");
      out.write("\n");
      out.write("\t\t\t\tdata = JSON.stringify(data);\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\ttype : type,\n");
      out.write("\t\t\t\t\turl : url,\n");
      out.write("\t\t\t\t\tdata : data,\n");
      out.write("\t\t\t\t\tasync : async,\n");
      out.write("\t\t\t\t\theaders : headers,\n");
      out.write("\t\t\t\t\txhrFields : {\n");
      out.write("\t\t\t\t\t\twithCredentials : true\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\tsuccess : getCitasOK,\n");
      out.write("\t\t\t\t\terror : getCitasError\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction getCitasOK(respuesta) {\n");
      out.write("\t\t\tconsole.log(respuesta);\n");
      out.write("\t\t\tvar jsoHorasOcu = JSON.parse(respuesta);\n");
      out.write("\t\t\tsessionStorage.horasOcupadas = JSON.stringify(jsoHorasOcu);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction getCitasError(e){\n");
      out.write("\t\t\tconsole.log(e)\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction rellenarHoras(){\n");
      out.write("\t\t\t$('#hora').empty()\n");
      out.write("\t\t\tvar select = document.getElementById(\"hora\");\n");
      out.write("\t\t\tvar jsoHoras = JSON.parse(sessionStorage.horas);\n");
      out.write("\t\t\tfor(var i = 0; i <jsoHoras.length ; i++) {\n");
      out.write("\t\t\t  \tvar option = document.createElement('option');\n");
      out.write("\t\t\t  \toption.text = option.value = jsoHoras[i];\n");
      out.write("\t\t\t   \tselect.add(option, 0);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction getDNIMedico(especialidadSeleccionada){\n");
      out.write("\t\t\tvar jsoGrupo = JSON.parse(sessionStorage.usuario);\n");
      out.write("\t\t\tvar listaMedicos = jsoGrupo.resultado.grupoMedico.listaMedicos;\n");
      out.write("\t\t\tconsole.log(listaMedicos[1].especialidad);\n");
      out.write("\t\t\tfor(var i=0; i<listaMedicos.length; i++){\n");
      out.write("\t\t\t\tif (listaMedicos[i].especialidad == especialidadSeleccionada){\n");
      out.write("\t\t\t\t\tvar dniMedico = listaMedicos[i].DNI;\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tconsole.log(dniMedico);\n");
      out.write("\t\t\tsolicitarHorarioMedico(dniMedico);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction solicitarHorarioMedico(dniMedico) {\n");
      out.write("\t\t\tvar data = {\n");
      out.write("\t\t\t\t\tdniMedico : dniMedico,\n");
      out.write("\t\t\t\t\ttipo : \"solicitar\"\n");
      out.write("\t\t\t\t};\n");
      out.write("\t\t\t\tvar url = \"/formularioCitas\";\n");
      out.write("\t\t\t\tvar type = \"POST\";\n");
      out.write("\t\t\t\tvar success;\n");
      out.write("\t\t\t\tvar async= false;\n");
      out.write("\t\t\t\tvar xhrFields;\n");
      out.write("\t\t\t\tvar headers = {\n");
      out.write("\t\t\t\t\t'Content-Type' : 'application/json'\n");
      out.write("\t\t\t\t};\n");
      out.write("\n");
      out.write("\t\t\t\tdata = JSON.stringify(data);\n");
      out.write("\t\t\t\tconsole.log(data);\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\ttype : type,\n");
      out.write("\t\t\t\t\turl : url,\n");
      out.write("\t\t\t\t\tdata : data,\n");
      out.write("\t\t\t\t\tasync : async,\n");
      out.write("\t\t\t\t\theaders : headers,\n");
      out.write("\t\t\t\t\txhrFields : {\n");
      out.write("\t\t\t\t\t\twithCredentials : true\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\tsuccess : solicitarOK,\n");
      out.write("\t\t\t\t\terror : solicitarError\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction solicitarOK(respuesta){\n");
      out.write("\t\t\tconsole.log(respuesta);\n");
      out.write("\t\t\tvar jsoHorarioM = JSON.parse(respuesta);\n");
      out.write("\t\t\tconsole.log(jsoHorarioM);\n");
      out.write("\t\t\tconsole.log(jsoHorarioM.horarioMedico.horario);\n");
      out.write("\t\t\tvar arrayHorario = jsoHorarioM.horarioMedico.horario;\n");
      out.write("\t\t\tdocument.getElementById(\"fecha_ini\").disabled=false;\n");
      out.write("\t\t\tsessionStorage.horario=JSON.stringify(jsoHorarioM);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction solicitarError(error){\n");
      out.write("\t\t\tconsole.log(error);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tfunction cargarDatosFormulario() {\n");
      out.write("\t\t\tvar select = document.getElementById(\"especialidad\");\n");
      out.write("\t\t\tvar jsoUser = JSON.parse(sessionStorage.usuario);\n");
      out.write("\t\t\tconsole.log(sessionStorage.usuario);\n");
      out.write("\t\t\tvar numEspecialidades = jsoUser.resultado.grupoMedico.listaMedicos.length;\n");
      out.write("\t\t\tfor(var i = 0; i <=numEspecialidades ; i++) {\n");
      out.write("\t\t\t  \tvar option = document.createElement('option');\n");
      out.write("\t\t\t  \toption.text = option.value = jsoUser.resultado.grupoMedico.listaMedicos[i].especialidad;\n");
      out.write("\t\t\t   \tselect.add(option, 0);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction enviarDatos() {\n");
      out.write("\t\t\tvar jsoUser = JSON.parse(sessionStorage.usuario);\n");
      out.write("\t\t\tvar jsoHorario = JSON.parse(sessionStorage.horario);\n");
      out.write("\t\t\tvar data = {\n");
      out.write("\t\t\t\tdniPaciente : jsoUser.resultado.usuario.dni,\n");
      out.write("\t\t\t\tdniMedico : jsoHorario.horarioMedico.DNI,\n");
      out.write("\t\t\t\tdia : $('#fecha_ini').val(),\n");
      out.write("\t\t\t\thora : $('#hora').val(),\n");
      out.write("\t\t\t\ttipo : \"enviarCita\"\n");
      out.write("\t\t\t};\n");
      out.write("\t\t\tvar url = \"/formularioCitas\";\n");
      out.write("\t\t\tvar type = \"POST\";\n");
      out.write("\t\t\tvar success;\n");
      out.write("\t\t\tvar xhrFields;\n");
      out.write("\t\t\tvar headers = {\n");
      out.write("\t\t\t\t'Content-Type' : 'application/json'\n");
      out.write("\t\t\t};\n");
      out.write("\n");
      out.write("\t\t\tdata = JSON.stringify(data);\n");
      out.write("\t\t\tconsole.log(data);\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype : type,\n");
      out.write("\t\t\t\turl : url,\n");
      out.write("\t\t\t\tdata : data,\n");
      out.write("\t\t\t\theaders : headers,\n");
      out.write("\t\t\t\txhrFields : {\n");
      out.write("\t\t\t\t\twithCredentials : true\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\tsuccess : PedirCitaOK,\n");
      out.write("\t\t\t\terror : PedirCitaError\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction PedirCitaOK(respuesta) {\n");
      out.write("\t\t\tconsole.log(\"Cita OK\");\n");
      out.write("\t\t\tswal({\n");
      out.write("\t\t\t\ttitle : \"Solicitud recibida\",\n");
      out.write("\t\t\t\ttext : \"Has añadido una cita\",\n");
      out.write("\t\t\t\ticon : \"success\",\n");
      out.write("\t\t\t}).then(function() {\n");
      out.write("\t\t\t\twindow.location.href = \"/citas\";\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction PedirCitaError() {\n");
      out.write("\t\t\t$('#especialidad').val(\"\");\n");
      out.write("\t\t\t$('#fecha_ini').val(\"\");\n");
      out.write("\t\t\t$('#hora').val(\"\");\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction comprobarHora(texto) {\n");
      out.write("\t\t\tdocument.getElementById(\"noHayHora\").style.display = 'none';\n");
      out.write("\t\t\tif (texto == '') {\n");
      out.write("\t\t\t\tdocument.getElementById(\"noHayHora\").style.display = 'inline';\n");
      out.write("\t\t\t\t$('#noHayHora').html(\"Tiene que escoger una hora para su cita.\");\n");
      out.write("\t\t\t\t$('#noHayHora').css(\"color\", \"red\");\n");
      out.write("\t\t\t\treturn 1;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn 0;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tfunction comprobarFecha(texto) {\n");
      out.write("\t\t\tdocument.getElementById(\"fecha\").style.display = 'none';\n");
      out.write("\t\t\tif (texto == '') {\n");
      out.write("\t\t\t\tdocument.getElementById(\"fecha\").style.display = 'inline';\n");
      out.write("\t\t\t\t$('#fecha').html(\"Tiene que escoger un día para su cita.\");\n");
      out.write("\t\t\t\t$('#fecha').css(\"color\", \"red\");\n");
      out.write("\t\t\t\treturn 1;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\treturn 0;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t$('#fecha_ini').datepicker({\n");
      out.write("\t\t\tformat : \"dd/mm/yyyy\",\n");
      out.write("\t\t\tstartDate : 'd',\n");
      out.write("\t\t\tendDate : \"31/12/2020\",\n");
      out.write("\t\t\ttodayBtn : \"linked\",\n");
      out.write("\t\t\tlanguage : \"es\",\n");
      out.write("\t\t\ttodayHighlight : true\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
