/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-11-01 09:47:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\n");
      out.write("    <meta name=\"description\" content=\"\">\n");
      out.write("    <meta name=\"author\" content=\"\">\n");
      out.write("    <link rel=\"icon\" href=\"../../favicon.ico\">\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/3.4/examples/signin/\">\n");
      out.write("\n");
      out.write("    <title>Registro</title>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap core CSS -->\n");
      out.write("     <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\n");
      out.write("  \t \n");
      out.write("  \t <link rel=\"stylesheet\" href=\"datePicker/css/bootstrap-datepicker.css\">\n");
      out.write("    <script src=\"datePicker/js/bootstrap-datepicker.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.js\"></script>\n");
      out.write("    \n");
      out.write("    <script src=\"datePicker/locales/bootstrap-datepicker.es.min.js\"></script>\n");
      out.write("   \n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/css/bootstrap-datepicker3.min.css\">\n");
      out.write("  \t \n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\n");
      out.write("    <link href=\"../../assets/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("    <link href=\"signin.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\n");
      out.write("    <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\n");
      out.write("    <script src=\"../../assets/js/ie-emulation-modes-warning.js\"></script>\n");
      out.write("\n");
      out.write("    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->\n");
      out.write("    <!--[if lt IE 9]>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js\"></script>\n");
      out.write("      <script src=\"https://oss.maxcdn.com/respond/1.4.2/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("        $( document ).ready(function() {\n");
      out.write("            $('#fecha').datepicker();\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("  </head>\n");
      out.write("\n");
      out.write("  <style>\n");
      out.write("      .bd-placeholder-img {\n");
      out.write("        font-size: 1.125rem;\n");
      out.write("        text-anchor: middle;\n");
      out.write("        -webkit-user-select: none;\n");
      out.write("        -moz-user-select: none;\n");
      out.write("        -ms-user-select: none;\n");
      out.write("        user-select: none;\n");
      out.write("      }\n");
      out.write("\n");
      out.write("      @media (min-width: 768px) {\n");
      out.write("        .bd-placeholder-img-lg {\n");
      out.write("          font-size: 3.5rem;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("    </style>\n");
      out.write("    <!-- Custom styles for this template -->\n");
      out.write("    <link href=\"starter-template.css\" rel=\"stylesheet\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    <nav class=\"navbar navbar-expand-md navbar-dark bg-dark fixed-top\">\n");
      out.write("  <a class=\"navbar-brand\" href=\"/\">Registro</a>\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarsExampleDefault\" aria-controls=\"navbarsExampleDefault\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("  </button>\n");
      out.write("</nav>\n");
      out.write("\n");
      out.write("<main role=\"main\" class=\"container\">\n");
      out.write("\t<div class=\"span\">\n");
      out.write("\t<div></div>\n");
      out.write("          <div class=\"hero-unit\">\n");
      out.write("    \t\t<br></br></br></br>\n");
      out.write("    \t<div class=\"row\">\n");
      out.write("  \t\t\t<div class=\"col-md-8\">\n");
      out.write("  \t\t\t\n");
      out.write("\t\t\t\t<div class=\"card\">\n");
      out.write("  \t\t\t\t<div class=\"card-body\">\n");
      out.write("            \t\t<h4>Registro</h4>\n");
      out.write("            \t\t<p>Bienvenido/a a la página de registro. Por favor rellene todos los campos que encontrará a continuación, después pulse en el botón de Enviar.</p>\n");
      out.write("         \t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"col-md-1\"></div>\n");
      out.write("          </div>\n");
      out.write("     <br></br>\n");
      out.write("  </div>\n");
      out.write("\t \n");
      out.write("\t  <div class=\"col-md-8 order-md-1\">\n");
      out.write("      <form class=\"needs-validation\" novalidate>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 mb-3\">\n");
      out.write("            <label for=\"nombre\">Nombre</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"nombre\" placeholder=\"\" value=\"\" required>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("              Información necesaria.\n");
      out.write("            </div>\n");
      out.write("            <label id=\"labelNombreMal\"></label>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-6 mb-3\">\n");
      out.write("            <label for=\"apellidos\">Apellidos</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"apellidos\" placeholder=\"\" value=\"\" required>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("              Información necesaria.\n");
      out.write("            </div>\n");
      out.write("            <label id=\"labelApellidosMal\"></label>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"dni\">DNI</label>\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"dni\" placeholder=\"00000000X\" required>\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelDNIMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"fecha_ini\">Fecha de nacimiento</label>\n");
      out.write("          <input type=\"text\" id=\"fecha_ini\" class=\"form-control\">\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelFechaMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"domicilio\">Domicilio</label>\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"domicilio\" placeholder=\"Calle de residencia N0 0X\" required>\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelDomicilioMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-md-6 mb-3\">\n");
      out.write("            <label for=\"poblacion\">Población</label>\n");
      out.write("            <select class=\"custom-select d-block w-100\" id=\"poblacion\" required>\n");
      out.write("              <option value=\"\">Elige...</option>\n");
      out.write("              <option>Álava</option>\n");
      out.write("              <option>Albacete</option>\n");
      out.write("              <option>Alicante</option>\n");
      out.write("              <option>Almería</option>\n");
      out.write("              <option>Asturias</option>\n");
      out.write("              <option>Ávila</option>\n");
      out.write("              <option>Badajoz</option>\n");
      out.write("              <option>Barcelona</option>\n");
      out.write("              <option>Burgos</option>\n");
      out.write("              <option>Cáceres</option>\n");
      out.write("              <option>Cádiz</option>\n");
      out.write("              <option>Cantabria</option>\n");
      out.write("              <option>Castellón</option>\n");
      out.write("              <option>Ceuta</option>\n");
      out.write("              <option>Ciudad Real</option>\n");
      out.write("              <option>Córdoba</option>\n");
      out.write("              <option>Cuenca</option>\n");
      out.write("              <option>Gerona</option>\n");
      out.write("              <option>Granada</option>\n");
      out.write("              <option>Guadalajara</option>\n");
      out.write("              <option>Guipúzcoa</option>\n");
      out.write("              <option>Huelva</option>\n");
      out.write("              <option>Huesca</option>\n");
      out.write("              <option>Islas Baleares</option>\n");
      out.write("              <option>Jaén</option>\n");
      out.write("              <option>La Coruña</option>\n");
      out.write("              <option>La Rioja</option>\n");
      out.write("              <option>Las Palmas</option>\n");
      out.write("              <option>León</option>\n");
      out.write("              <option>Lérida</option>\n");
      out.write("              <option>Lugo</option>\n");
      out.write("              <option>Madrid</option>\n");
      out.write("              <option>Málaga</option>\n");
      out.write("              <option>Melilla</option>\n");
      out.write("              <option>Murcia</option>\n");
      out.write("              <option>Navarra</option>\n");
      out.write("              <option>Orense</option>\n");
      out.write("              <option>Palencia</option>\n");
      out.write("              <option>Pontevedra</option>\n");
      out.write("              <option>Salamanca</option>\n");
      out.write("              <option>Segovia</option>\n");
      out.write("              <option>Sevilla</option>\n");
      out.write("              <option>Soria</option>\n");
      out.write("              <option>Tarragona</option>\n");
      out.write("              <option>Tenerife</option>\n");
      out.write("              <option>Teruel</option>\n");
      out.write("              <option>Toledo</option>\n");
      out.write("              <option>Valencia</option>\n");
      out.write("              <option>Valladolid</option>\n");
      out.write("              <option>Vizcaya</option>\n");
      out.write("              <option>Zamora</option>\n");
      out.write("              <option>Zaragoza</option>\n");
      out.write("            </select>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("              Información necesaria.\n");
      out.write("            </div>\n");
      out.write("            <label id=\"labelPoblacionMal\"></label>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-md-6 mb-3\">\n");
      out.write("            <label for=\"cp\">Código postal</label>\n");
      out.write("            <input type=\"text\" class=\"form-control\" id=\"cp\" placeholder=\"\" value=\"\" required>\n");
      out.write("            <div class=\"invalid-feedback\">\n");
      out.write("              Información necesaria.\n");
      out.write("            </div>\n");
      out.write("            <label id=\"labelCpMal\"></label>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"telefono\">Teléfono<span class=\"text-muted\"></span></label>\n");
      out.write("          <input type=\"telefono\" class=\"form-control\" id=\"telefono\" placeholder=\"\">\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelTelefonoMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"email\">Correo electrónico<span class=\"text-muted\">(Optional)</span></label>\n");
      out.write("          <input type=\"email\" class=\"form-control\" id=\"email\" placeholder=\"tu@ejemplo.com\">\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelEmailMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"contraseña1\">Contraseña<span class=\"text-muted\"></span></label>\n");
      out.write("          <input type=\"password\" class=\"form-control\" id=\"contraseña\" placeholder=\"\">\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelContraseñaMal\"></label>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div class=\"mb-3\">\n");
      out.write("          <label for=\"contraseña2\">Repita la contraseña<span class=\"text-muted\"></span></label>\n");
      out.write("          <input type=\"password\" class=\"form-control\" id=\"RepetirContraseña\" placeholder=\"\">\n");
      out.write("          <div class=\"invalid-feedback\">\n");
      out.write("            Información necesaria.\n");
      out.write("          </div>\n");
      out.write("          <label id=\"labelRepetirContraseñaMal\"></label>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <hr class=\"mb-4\">\n");
      out.write("        <a id = \"registrarUsuario\" class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">Enviar</a>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("\t \n");
      out.write("  <br>\n");
      out.write("  </div>\n");
      out.write("  </br>\n");
      out.write("\n");
      out.write("</main><!-- /.container -->\n");
      out.write("  \n");
      out.write("\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.min.js\"></script>\n");
      out.write("    \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("    jQuery(document).ready(function($) {\n");
      out.write("    \t$('#registrarUsuario').click(function(event) {\n");
      out.write("    \t\tif(!(comprobarNombre(document.getElementById(\"nombre\").value) + comprobarApellidos(document.getElementById(\"apellidos\").value) + comprobarDNI(document.getElementById(\"dni\").value) + comprobarFecha(document.getElementById(\"fecha_ini\").value) + comprobarDomicilio(document.getElementById(\"domicilio\").value) + comprobarPoblacion(document.getElementById(\"poblacion\").value) + comprobarCp(document.getElementById(\"cp\").value) + comprobarTelefono(document.getElementById(\"telefono\").value) + comprobarEmail(document.getElementById(\"email\").value) + comprobarContraseña(document.getElementById(\"contraseña\").value) + comprobarRepetirContraseña(document.getElementById(\"RepetirContraseña\").value) + coincidenContraseñas(document.getElementById(\"contraseña\").value, document.getElementById(\"RepetirContraseña\").value)) != 0){\n");
      out.write("    \t\t\tevent.preventDefault();\n");
      out.write("        \t\tenviarDatos();\n");
      out.write("    \t\t}\n");
      out.write("    \t});\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var caracterInvalido=\"0123456789ºª\\!|@·#$%&¬/()=?¿¡/*-+,;:^\";\n");
      out.write("    \n");
      out.write("\tfunction enviarDatos(){\n");
      out.write("\t\tvar data = {\n");
      out.write("\t\t\tnombre : $('#nombre').val(),\n");
      out.write("\t\t\tapellidos : $('#apellidos').val(),\n");
      out.write("\t\t\tDNI : $('#dni').val(),\n");
      out.write("\t\t\tnacimiento : $('#fecha_ini').val(),\n");
      out.write("\t\t\tdomicilio : $('#domicilio').val(),\n");
      out.write("\t\t\tpoblacion : $('#poblacion').val(),\n");
      out.write("\t\t\tcp : $('#cp').val(),\n");
      out.write("\t\t\ttelefono : $('#telefono').val(),\n");
      out.write("\t\t\temail : $('#email').val(),\n");
      out.write("\t\t\tpassword : $('#contraseña').val(),\n");
      out.write("\t\t\t\n");
      out.write("\t\t};\n");
      out.write("\t\tvar url = \"/registro\";\n");
      out.write("\t\tvar type = \"POST\";\n");
      out.write("\t\tvar success;\n");
      out.write("\t\tvar xhrFields;\n");
      out.write("\t\tvar headers = {\n");
      out.write("\t\t\t'Content-Type' : 'application/json'\n");
      out.write("\t\t};\n");
      out.write("\t\t\n");
      out.write("\t\tdata = JSON.stringify(data);\n");
      out.write("\t\tconsole.log(data);\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\ttype: type,\n");
      out.write("\t\t\turl: url,\n");
      out.write("\t\t\tdata: data,\n");
      out.write("\t        headers : headers,\n");
      out.write("\t        xhrFields: {\n");
      out.write("\t            withCredentials: true\n");
      out.write("\t        },\n");
      out.write("\t        success : RegisterOK,\n");
      out.write("\t        error : RegisterError\n");
      out.write("\t\t});\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tfunction RegisterOK() {\n");
      out.write("        console.log(\"Registro completado\");\n");
      out.write("        var forma = document.forms[0];\n");
      out.write("        forma.action=\"/citas\";\n");
      out.write("        forma.submit(); \n");
      out.write("    }\n");
      out.write("\t\n");
      out.write("\tfunction RegisterError() {\n");
      out.write("        console.log(\"Ya existe el dni\");\n");
      out.write("        window.alert(\"El DNI que ha introducido ya está en uso.\");\n");
      out.write("        $('#nombre').val(\"\");\n");
      out.write("        $('#apellidos').val(\"\");\n");
      out.write("        $('#dni').val(\"\");\n");
      out.write("        $('#fecha_ini').val(\"\");\n");
      out.write("        $('#domicilio').val(\"\");\n");
      out.write("        $('#poblacion').val(\"\");\n");
      out.write("        $('#cp').val(\"\");\n");
      out.write("        $('#telefono').val(\"\");\n");
      out.write("        $('#email').val(\"\");\n");
      out.write("        $('#contraseña').val(\"\");\n");
      out.write("        $('#RepetirContraseña').val(\"\");\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function comprobarNombre(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelNombreMal\").style.display = 'none';\n");
      out.write("      \t\t\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelNombreMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelNombreMal').html(\"El nombre es obligatorio.\");\n");
      out.write("       \t        $('#labelNombreMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("\n");
      out.write("       \t   for(i=0; i<texto.length; i++){\n");
      out.write("       \t      if (caracterInvalido.indexOf(texto.charAt(i),0)!=-1){\n");
      out.write("       \t    \tdocument.getElementById(\"labelNombreMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelNombreMal').html(\"El nombre no es válido.\");\n");
      out.write("       \t        $('#labelNombreMal').css(\"color\", \"red\");\n");
      out.write("       \t         return 1;  //si devuelve 1 es un caracter invalido,  ver si es necesario que tenga return\n");
      out.write("       \t      }\n");
      out.write("       \t   }\n");
      out.write("       \t   return 0;  //si devuelve 0 es porque vale\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarApellidos(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelApellidosMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelApellidosMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelApellidosMal').html(\"Los apellidos son obligatorios.\");\n");
      out.write("       \t        $('#labelApellidosMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("       \t\tfor(i=0; i<texto.length; i++){\n");
      out.write("       \t      if (caracterInvalido.indexOf(texto.charAt(i),0)!=-1){\n");
      out.write("       \t    \tdocument.getElementById(\"labelApellidosMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelApellidosMal').html(\"Los apellidos no son válidos.\");\n");
      out.write("       \t        $('#labelApellidosMal').css(\"color\", \"red\");\n");
      out.write("       \t        return 1;  //si devuelve 1 es un caracter invalido,  ver si es necesario que tenga return\n");
      out.write("       \t      }\n");
      out.write("       \t   }\n");
      out.write("       \t   return 0;  //si devuelve 0 es porque vale\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarDNI(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelDNIMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelDNIMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelDNIMal').html(\"El DNI es obligatorio.\");\n");
      out.write("       \t        $('#labelDNIMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\tif (texto.length != 9) {\n");
      out.write("       \t    \tdocument.getElementById(\"labelDNIMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelDNIMal').html(\"El DNI no es válido.\");\n");
      out.write("       \t        $('#labelDNIMal').css(\"color\", \"red\");\n");
      out.write("       \t        return 1;  //si devuelve 1 es un caracter invalido,  ver si es necesario que tenga return\n");
      out.write("      \t\t}\n");
      out.write("      \t\tfor(i=0; i<texto.length; i++){\n");
      out.write("      \t\t\tif (i==8){\n");
      out.write("      \t\t\t\tif (/[A-Z]/.test(texto.charAt(i)) == false) {\n");
      out.write("      \t       \t    \tdocument.getElementById(\"labelDNIMal\").style.display = 'inline';\n");
      out.write("      \t       \t        $('#labelDNIMal').html(\"El DNI no es válido.\");\n");
      out.write("      \t       \t        $('#labelDNIMal').css(\"color\", \"red\");\n");
      out.write("      \t       \t        return 1;\n");
      out.write("      \t\t\t\t}\n");
      out.write("      \t\t\t}\n");
      out.write("      \t\t\telse{\n");
      out.write("      \t\t\t\tif (isNaN(texto.charAt(i)) == true) {\n");
      out.write("      \t       \t    \tdocument.getElementById(\"labelDNIMal\").style.display = 'inline';\n");
      out.write("      \t       \t        $('#labelDNIMal').html(\"El DNI no es válido.\");\n");
      out.write("      \t       \t        $('#labelDNIMal').css(\"color\", \"red\");\n");
      out.write("      \t       \t        return 1;\n");
      out.write("      \t\t\t\t}\n");
      out.write("      \t\t\t}\n");
      out.write("      \t\t}\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarFecha(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelFechaMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelFechaMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelFechaMal').html(\"La fecha de nacimiento es obligatoria.\");\n");
      out.write("       \t        $('#labelFechaMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarDomicilio(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelDomicilioMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelDomicilioMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelDomicilioMal').html(\"El domicilio es obligatorio.\");\n");
      out.write("       \t        $('#labelDomicilioMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarPoblacion(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelPoblacionMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelPoblacionMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelPoblacionMal').html(\"La población es obligatoria.\");\n");
      out.write("       \t        $('#labelPoblacionMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarCp(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelCpMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelCpMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelCpMal').html(\"El código postal es obligatorio.\");\n");
      out.write("       \t        $('#labelCpMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\tif (isNaN(texto) == true) {\n");
      out.write("       \t    \tdocument.getElementById(\"labelCpMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelCpMal').html(\"El código postal no es válido.\");\n");
      out.write("       \t        $('#labelCpMal').css(\"color\", \"red\");\n");
      out.write("       \t        return 1;  //si devuelve 1 es un caracter invalido,  ver si es necesario que tenga return\n");
      out.write("      \t\t}\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarTelefono(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelTelefonoMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelTelefonoMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelTelefonoMal').html(\"El telefono es obligatorio.\");\n");
      out.write("       \t        $('#labelTelefonoMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\tif (isNaN(texto) == true) {\n");
      out.write("       \t    \tdocument.getElementById(\"labelTelefonoMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelTelefonoMal').html(\"El telefono no es válido.\");\n");
      out.write("       \t        $('#labelTelefonoMal').css(\"color\", \"red\");\n");
      out.write("       \t        return 1;  //si devuelve 1 es un caracter invalido,  ver si es necesario que tenga return\n");
      out.write("      \t\t}\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarEmail(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelEmailMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelEmailMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelEmailMal').html(\"El correo electrónico es obligatorio.\");\n");
      out.write("       \t        $('#labelEmailMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarContraseña(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelContraseñaMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelContraseñaMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelContraseñaMal').html(\"La contraseña es obligatoria.\");\n");
      out.write("       \t        $('#labelContraseñaMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction comprobarRepetirContraseña(texto){\n");
      out.write("      \t\tdocument.getElementById(\"labelRepetirContraseñaMal\").style.display = 'none';\n");
      out.write("      \t\tif (texto == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelRepetirContraseñaMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelRepetirContraseñaMal').html(\"La repetición de contraseña es obligatoria.\");\n");
      out.write("       \t        $('#labelRepetirContraseóaMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\t\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("      \t\n");
      out.write("      \tfunction coincidenContraseñas(c1, c2){\n");
      out.write("      \t\tdocument.getElementById(\"labelRepetirContraseñaMal\").style.display = 'none';\n");
      out.write("      \t\tif (c2 == '') {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelRepetirContraseñaMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelRepetirContraseñMal').html(\"La repetición de contraseña es obligatoria.\");\n");
      out.write("       \t        $('#labelRepetirContraseñaMal').css(\"color\", \"red\");\n");
      out.write("      \t\t\treturn 1;\n");
      out.write("      \t\t}\n");
      out.write("\n");
      out.write("\t\t\tif (c1 != c2) {\n");
      out.write("      \t\t\tdocument.getElementById(\"labelRepetirContraseñaMal\").style.display = 'inline';\n");
      out.write("       \t        $('#labelRepetirContraseñaMal').html(\"Las contraseñas no coinciden, inténtalo de nuevo.\");\n");
      out.write("       \t        $('#labelRepetirContraseñaMal').css(\"color\", \"red\");\n");
      out.write("       \t     \treturn 1;\n");
      out.write("\t\t\t}\n");
      out.write("      \t\treturn 0;\n");
      out.write("      \t}\n");
      out.write("    </script>\n");
      out.write("  \t<script>\n");
      out.write("\n");
      out.write("  \t\t$('#fecha_ini').datepicker({\n");
      out.write("        \tformat: \"dd/mm/yyyy\",\n");
      out.write("        \tstartDate: \"1/1/1900\",\n");
      out.write("        \tendDate: \"13/10/2019\",\n");
      out.write("        \ttodayBtn: \"linked\",\n");
      out.write("        \tlanguage: \"es\",\n");
      out.write("        \ttodayHighlight: true\n");
      out.write("    \t});\n");
      out.write("\n");
      out.write("  </script>\n");
      out.write("  </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
